---

- name: install docker
  yum:
    name:
      - docker
    state: present
  become: yes

- name: restart docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
  become: yes
