# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

begin
  conf = YAML.load_file(File.join(File.dirname(__FILE__), 'config.yml'))
rescue Errno::ENOENT => ex
  STDERR.puts ex
  STDERR.puts 'Create config.yml at the same dir with Vagrantfile'
  exit(false)
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = conf['vbox_image']

  config.vm.usable_port_range = 2000..19999
  config.vm.network "forwarded_port", guest: 80, host: conf['default_port'], host_ip: conf['host_ip'], id: "Product", auto_correct: true
  config.vm.network "forwarded_port", guest: 8000, host: conf['tabby_default_port'], host_ip: conf['host_ip'], id: "tabby default", auto_correct: true

  config.vm.network "private_network", ip: conf['private_ip']

  config.vm.synced_folder conf['shared_folder'], "/vagrant_data"
  config.vm.synced_folder "../provision", "/provision", type: "virtualbox", owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = conf['vbox_instance_name']
    vb.memory = conf['vbox_instance_memory']
    vb.gui = conf['vbox_instance_gui']
  end

  # [Machine Setting] Run shell script on guest machine.
  config.vm.provision "shell", inline: <<-SHELL
    
    # install ansible
    sudo yum -y install ansible
  SHELL

  # [VM provisioning] Run Ansible from the Vagrant Host
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook =  "/provision/" + conf['env_type'] + ".yml"
  end
end
