# config file
---

#---------------------
# Vbox infomation
#---------------------

vbox_image: "bento/centos-7.5"
vbox_instance_name: "deploy"
vbox_instance_memory: "2048"
vbox_instance_gui: "true"

#---------------------
# Network
#---------------------

# ip
host_ip: "127.0.0.1"
private_ip: "192.168.10.200"

# Portfoward
default_port: "8080"		# 80

#---------------------
# Other
#---------------------

env_type: "deploy"
shared_folder: "./data"
