# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
 begin
  conf = YAML.load_file(File.join(File.dirname(__FILE__), 'config.yml'))
rescue Errno::ENOENT => ex
  STDERR.puts ex
  STDERR.puts 'Create config.yml at the same dir with Vagrantfile'
  exit(false)
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = conf['vbox_image']

  config.vm.usable_port_range = 2000..19999
  config.vm.network "forwarded_port", guest: 80, host: conf['default_port'], host_ip: conf['host_ip'], id: "Product", auto_correct: true
  
  config.vm.network "private_network", ip: conf['private_ip']

  config.vm.synced_folder conf['shared_folder'], "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = conf['vbox_instance_name']
    vb.memory = conf['vbox_instance_memory']
    vb.gui = conf['vbox_instance_gui']
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     sudo yum -y groupinstall "GNOME Desktop"
     sudo systemctl set-default graphical.target
     systemctl get-default
     
     sudo shutdown -r now
  SHELL
end
