# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

begin
  conf = YAML.load_file(File.join(File.dirname(__FILE__), 'config.yml'))
rescue Errno::ENOENT => ex
  STDERR.puts ex
  STDERR.puts 'Create config.yml at the same dir with Vagrantfile'
  exit(false)
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = conf['vbox_image']

  config.vm.usable_port_range = 2000..19999
  config.vm.network "forwarded_port", guest: 80, host: conf['default_port'], host_ip: conf['host_ip'], id: "Product", auto_correct: true
  config.vm.network "forwarded_port", guest: 10080, host: conf['gitlab_port'], host_ip: conf['host_ip'], id: "GitLab", auto_correct: true
  config.vm.network "forwarded_port", guest: 10022, host: conf['gitlab_ssh_port'], host_ip: conf['host_ip'],  id: "GitLab-ssh", auto_correct: true
  
  config.vm.network "private_network", ip: conf['private_ip']

  config.vm.synced_folder conf['shared_folder'], "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.name = conf['vbox_instance_name']
     vb.memory = conf['vbox_instance_memory']
     vb.gui = conf['vbox_instance_gui']
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     sudo yum -y groupinstall "GNOME Desktop"
     sudo yum install gcc zlib-devel bzip2 bzip2-devel readline readline-devel  openssl openssl-devel git
     sudo systemctl set-default graphical.target
     sudo systemctl get-default
     
     # install docker
     sudo yum install -y docker
     sudo systemctl enable docker
     sudo systemctl start docker
     
     # run gitla
     sudo docker run --name gitlab-postgresql -d --env 'DB_NAME=gitlabhq_production' --env 'DB_USER=gitlab' --env 'DB_PASS=password' --env 'DB_EXTENSION=pg_trgm' --volume /srv/docker/gitlab/postgresql:/var/lib/postgresql sameersbn/postgresql:10
     sudo docker run --name gitlab-redis -d --volume /srv/docker/gitlab/redis:/var/lib/redis sameersbn/redis:4.0.9-1
     sudo docker run --name gitlab -d     --link gitlab-postgresql:postgresql --link gitlab-redis:redisio --publish 10022:22 --publish 10080:80 --env 'GITLAB_PORT=10080' --env 'GITLAB_SSH_PORT=10022' --env 'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string' --env 'GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string' --env 'GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string' --volume /srv/docker/gitlab/gitlab:/home/git/data sameersbn/gitlab:11.1.4
     sudo shutdown -r now
  SHELL
end
